In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

seg_df = pd.read_csv('http://bit.ly/PMR-ch5')



In [ ]:
#Testing Group Frequencies: scipy.stats.chisquare()

#Create test data for observations to look at frequency and chisquare
tmp = np.repeat(range(4),[25,25,25,20])
tmp

#Use nunique to get count of each value
tmp_values, tmp_counts = np.unique(tmp,return_counts = True)
tmp_counts

#Import scipy and stats
from scipy import stats
stats.chisquare(tmp_counts)
#Shows 85% chance of seeing a dataset with differences similar to ours

#changing observations to see a different number
tmp_values, tmp_counts = np.unique(np.repeat(range(4),[25,25,25,10]),
                                   return_counts = True)
print(tmp_counts)
print(stats.chisquare(tmp_counts))
print('Expected values: {}'.format(np.ones(4)*tmp_counts.sum()/4))

#Same data but 1/5 to see difference
tmp_counts_small = tmp_counts / 5
print(tmp_counts_small)
print(stats.chisquare(tmp_counts_small))
print('Expected values: {}'.format(np.ones(4)*tmp_counts_small.sum()/4))

#Looking at high differences
tmp_counts_large = tmp_counts * 10 + 1900
print(tmp_counts_large)
print(stats.chisquare(tmp_counts_large))
print('Expected values: {}'.format(np.ones(4)*tmp_counts_large.sum()/4))


#Looking at our segment data and chisquare - are they sig different? - Yes
segment_values, segment_counts = np.unique(seg_df.Segment,
                                           return_counts = True)
print(segment_counts)
stats.chisquare(segment_counts)

#Using the value_counts() to look at segment counts
seg_df.Segment.value_counts()

#value_counts can be passed directly to chisquare
stats.chisquare(seg_df.Segment.value_counts())

#Using crosstab() and test with chisquare_contigency()
pd.crosstab(seg_df.subscribe, columns = seg_df.own_home)
stats.chi2_contingency(pd.crosstab(seg_df.subscribe
                                   , columns = seg_df.own_home))
#Making more readable
sub_by_home = pd.crosstab(seg_df.subscribe, columns = seg_df.own_home)

print('chisq_stat: {0}\npavule: {1}\ndof: {2}\nexpected_values: {3}'
      .format(*stats.chi2_contingency(sub_by_home,
                                      correction = False)))



[25 25 25 10]
Power_divergenceResult(statistic=np.float64(7.9411764705882355), pvalue=np.float64(0.04724318343092867))
Expected values: [21.25 21.25 21.25 21.25]
[5. 5. 5. 2.]
Power_divergenceResult(statistic=np.float64(1.5882352941176472), pvalue=np.float64(0.6620603202525777))
Expected values: [4.25 4.25 4.25 4.25]
[2150 2150 2150 2000]
Power_divergenceResult(statistic=np.float64(7.988165680473372), pvalue=np.float64(0.04625691960442831))
Expected values: [2112.5 2112.5 2112.5 2112.5]
[ 70 100  80  50]
chisq_stat: 2.6737316360934784
pavule: 0.10201657409843726
dof: 1
expected_values: [[147.51666667 117.48333333]
 [ 19.48333333  15.51666667]]


In [18]:
#Testing Observed Proportions: binom_test()

from statsmodels.stats import proportion as sms_proportion

#Using statsmodels.proportion.binom_test() to get pvalue
sms_proportion.binom_test(count = 12, nobs = 20, prop = 0.5)

#Adding in a confidence level of 95%
sms_proportion.proportion_confint(count = 12, nobs = 20, alpha = 0.05)
#Shows the range which includes 50%, does not show more of one or the other

#Look at larger sample sizes binom_test()
sms_proportion.binom_test(count = 120, nobs = 200, prop = 0.5)

#Look at larger sample size CI 95%
sms_proportion.proportion_confint(count = 120, nobs = 200, alpha = 0.05)

#Using stats.binom and density estimate and sum point probs
stats.binom.pmf([8, 9, 10, 11, 12], p = 0.5, n = 20).sum()
stats.binom.pmf(range(8,13), p=0.5, n = 20).sum()

#Using proportion_confit- agresti_coull
sms_proportion.proportion_confint(0,20, method = 'agresti_coull')

(0.0, 0.18980956054248888)